"""Curated milestones and contributors for inventions beyond Section 1 entries 1.1–1.7."""
from __future__ import annotations

MILESTONES: dict[str, list[str]] = {
    "gunpowder": [
        "c. 850 CE — Chinese alchemists record a volatile mixture of saltpetre, sulfur, and charcoal (Tang Dynasty texts).",
        "10th century CE — Military use of gunpowder weapons in China (fire lances, bombs).",
        "13th century CE — Gunpowder knowledge spreads to the Islamic world and Europe via trade and Mongol campaigns.",
        "14th–15th century CE — European cannon and handheld firearms transform siege warfare and feudal fortifications.",
        "19th century onward — Gunpowder derivatives enable mining, quarrying, and civil engineering explosives.",
    ],
    "the-printing-press": [
        "c. 1040 CE — Bi Sheng invents movable-type printing in Song Dynasty China (clay type).",
        "c. 1377 CE — Jikji, Korean metal movable-type Buddhist text, among earliest surviving printed books.",
        "c. 1440 CE — Johannes Gutenberg develops oil-based ink, adjustable type mould, and press in Mainz.",
        "c. 1455 CE — Gutenberg Bible printed; movable type spreads across Europe within decades.",
        "16th century CE — Printing fuels the Renaissance, Reformation, and Scientific Revolution through mass literacy.",
    ],
    "the-scientific-method": [
        "c. 1021 CE — Ibn al-Haytham publishes Kitāb al-Manāẓir (Book of Optics), emphasising experiment and observation.",
        "1620 — Francis Bacon publishes Novum Organum, advocating inductive reasoning and systematic inquiry.",
        "1632–1642 — Galileo applies measurement and telescopic observation to celestial mechanics.",
        "1660 — Royal Society founded in London; peer review and reproducible experiment institutionalised.",
        "20th century — Karl Popper and others refine falsifiability; modern science adopts controlled trials and statistics.",
    ],
    "the-telescope": [
        "1608 — Hans Lipperhey applies for a Dutch patent for a refracting telescope.",
        "January 1610 — Galileo observes Jupiter's moons, lunar craters, and Venus phases, supporting heliocentrism.",
        "1668 — Isaac Newton builds the first practical reflecting telescope.",
        "1917 — 100-inch Hooker telescope at Mount Wilson enables Hubble's expanding-universe observations.",
        "2021 — James Webb Space Telescope launched; infrared astronomy probes the early universe.",
    ],
    "the-microscope": [
        "c. 1590 — Zacharias Janssen develops an early compound microscope in the Netherlands.",
        "1665 — Robert Hooke publishes Micrographia, revealing cellular structures in plants.",
        "1670s — Antoni van Leeuwenhoek observes bacteria, protozoa, and spermatozoa with single-lens microscopes.",
        "1931 — Ernst Ruska builds the first transmission electron microscope.",
        "21st century — Cryo-electron microscopy and super-resolution fluorescence achieve near-atomic biological imaging.",
    ],
    "newtonian-mechanics": [
        "1687 — Isaac Newton publishes Philosophiæ Naturalis Principia Mathematica (Principia).",
        "1687 — Three laws of motion and universal gravitation unify terrestrial and celestial mechanics.",
        "1680s — Newton and Leibniz independently develop calculus for continuous change.",
        "1740s–1800s — Euler, Lagrange, and Laplace extend classical mechanics to rigid bodies and fluids.",
        "20th century — Newtonian mechanics remains the engineering standard; superseded at extreme scales by relativity and quantum theory.",
    ],
    "steam-engine": [
        "1712 — Thomas Newcomen's atmospheric engine pumps water from Cornish mines.",
        "1769 — James Watt patents a separate condenser, dramatically improving efficiency.",
        "1804 — Richard Trevithick demonstrates a steam locomotive on rails in Wales.",
        "1825 — Stockton and Darlington Railway opens; steam powers the Industrial Revolution.",
        "19th century — Steam drives factories, ships, and railways; inaugurates large-scale fossil-fuel energy use.",
    ],
    "electricity-generation-and-distribution": [
        "1831 — Michael Faraday discovers electromagnetic induction, enabling mechanical-to-electrical conversion.",
        "1879 — Thomas Edison demonstrates practical incandescent lighting and builds Pearl Street Station (1882).",
        "1880s–1890s — Nikola Tesla and George Westinghouse develop AC systems for long-distance transmission.",
        "1930s — Rural electrification and national grids spread across industrialised nations.",
        "21st century — Smart grids integrate renewables, storage, and digital monitoring; ~750 million people still lack access.",
    ],
    "electromagnetism": [
        "1820 — Hans Christian Ørsted observes that electric current deflects a magnetic compass needle.",
        "1831 — Michael Faraday demonstrates electromagnetic induction and builds the first dynamo.",
        "1865 — James Clerk Maxwell publishes equations unifying electricity, magnetism, and light.",
        "1887 — Heinrich Hertz experimentally generates and detects radio waves predicted by Maxwell.",
        "20th century onward — Electromagnetic theory underpins motors, generators, radio, radar, and wireless communications.",
    ],
    "internal-combustion-engine": [
        "1859 — Étienne Lenoir builds the first commercially successful internal combustion engine.",
        "1876 — Nikolaus Otto patents the four-stroke (Otto) cycle engine.",
        "1897 — Rudolf Diesel patents the compression-ignition engine.",
        "1908 — Ford Model T mass production makes automobiles affordable worldwide.",
        "21st century — ICE vehicles face phase-out targets as electric drivetrains and emissions policy advance.",
    ],
    "automobile": [
        "1885 — Karl Benz patents the Benz Patent-Motorwagen, regarded as the first practical automobile.",
        "1890s — Gottlieb Daimler and Wilhelm Maybach develop high-speed petrol engines.",
        "1913 — Henry Ford introduces the moving assembly line, cutting Model T production time.",
        "20th century — Automobiles reshape cities, suburbs, petroleum industries, and global logistics.",
        "21st century — ~1.4 billion vehicles worldwide; safety, emissions, and electrification dominate policy debate.",
    ],
    "airplane": [
        "17 December 1903 — Wright brothers achieve sustained, controlled, powered flight at Kitty Hawk, North Carolina.",
        "1909 — Louis Blériot crosses the English Channel, proving aviation's practical potential.",
        "1937 — Frank Whittle patents the jet engine; Gloster E.28/39 flies in 1941.",
        "1958 — Boeing 707 inaugurates the jet age of commercial passenger travel.",
        "Pre-pandemic 2019 — Over 4 billion passengers flew annually; aviation connects global commerce and culture.",
    ],
    "refrigeration": [
        "1834 — Jacob Perkins patents a vapour-compression refrigeration cycle.",
        "1870s — Carl von Linde industrialises ammonia refrigeration for breweries and cold storage.",
        "1920s — Clarence Birdseye develops quick-freezing for commercial frozen foods.",
        "20th century — Domestic refrigerators become standard; cold chains enable global food and vaccine distribution.",
        "21st century — Refrigeration accounts for ~15% of global electricity use; natural refrigerants reduce climate impact.",
    ],
    "vaccination": [
        "1796 — Edward Jenner inoculates James Phipps with cowpox, demonstrating smallpox immunity.",
        "1885 — Louis Pasteur successfully vaccinates Joseph Meister against rabies.",
        "1955 — Jonas Salk's inactivated polio vaccine licensed in the United States.",
        "1980 — WHO certifies global eradication of smallpox.",
        "2020 — mRNA COVID-19 vaccines deployed within one year of sequence publication.",
    ],
    "antibiotics": [
        "1928 — Alexander Fleming observes penicillin's antibacterial effect in a Staphylococcus culture.",
        "1940 — Howard Florey and Ernst Chain purify penicillin at Oxford.",
        "1944 — Mass penicillin production supports Allied forces in World War II.",
        "1940s–1960s — Golden age of antibiotic discovery (streptomycin, tetracyclines, cephalosporins).",
        "21st century — Antimicrobial resistance named a top global health threat by WHO.",
    ],
    "germ-theory-of-disease": [
        "1847 — Ignaz Semmelweis demonstrates handwashing reduces puerperal fever mortality.",
        "1854 — John Snow traces a London cholera outbreak to the Broad Street pump.",
        "1861 — Louis Pasteur's swan-neck flask experiments refute spontaneous generation.",
        "1882–1884 — Robert Koch identifies tuberculosis and cholera bacilli; formulates Koch's postulates.",
        "20th century — Germ theory enables sterilisation, vaccines, antibiotics, and modern public health.",
    ],
    "anaesthesia": [
        "1842 — Crawford Long performs ether anaesthesia for surgery in Georgia (unpublished).",
        "16 October 1846 — William Morton demonstrates ether anaesthesia at Massachusetts General Hospital.",
        "1847 — James Young Simpson introduces chloroform for obstetric anaesthesia.",
        "20th century — Halothane and later agents enable safer general anaesthesia.",
        "Present — Balanced anaesthesia combines hypnotics, analgesics, and muscle relaxants with patient monitoring.",
    ],
    "x-rays-and-medical-imaging": [
        "8 November 1895 — Wilhelm Röntgen discovers X-rays in Würzburg, Germany.",
        "1901 — Röntgen awarded the first Nobel Prize in Physics.",
        "1971 — Godfrey Hounsfield and Allan Cormack develop computed tomography (CT).",
        "1977–1980s — Magnetic resonance imaging (MRI) enters clinical use.",
        "21st century — PET, ultrasound, functional MRI, and AI-assisted diagnosis extend non-invasive imaging.",
    ],
    "sanitation-and-clean-water-systems": [
        "1854 — John Snow's cholera investigation links disease to contaminated water.",
        "1858 — London's 'Great Stink' prompts parliamentary action on sewers.",
        "1860s–1870s — Joseph Bazalgette completes London's main sewer network.",
        "1908 — Jersey City, New Jersey, introduces municipal water chlorination.",
        "21st century — WHO reports ~2 billion people still lack safely managed drinking water.",
    ],
    "dna-structure-and-molecular-genetics": [
        "1944 — Oswald Avery, Colin MacLeod, and Maclyn McCarty identify DNA as the genetic material.",
        "1952 — Rosalind Franklin and Raymond Gosling produce Photo 51 (DNA X-ray diffraction).",
        "April 1953 — Watson and Crick publish the double-helix model in Nature.",
        "1962 — Nobel Prize awarded to Watson, Crick, and Wilkins.",
        "1970s onward — Recombinant DNA, PCR, and sequencing launch the biotechnology era.",
    ],
    "human-genome-sequencing": [
        "1990 — Human Genome Project officially launched as an international consortium.",
        "2001 — Draft human genome sequences published in Nature and Science.",
        "April 2003 — HGP declared complete with ~99% of the euchromatic genome.",
        "2022 — Telomere-to-telomere (T2T) consortium publishes a gapless human genome.",
        "2020s — Whole-genome sequencing costs fall below $200, enabling clinical and population genomics.",
    ],
    "crispr-gene-editing": [
        "1987 — Ishino et al. report clustered repeats in E. coli (origin of CRISPR acronym).",
        "2012 — Doudna, Charpentier, and colleagues programme Cas9 for targeted DNA cleavage.",
        "2015 — First CRISPR-edited human embryos reported (non-viable, research context).",
        "2020 — Nobel Prize in Chemistry awarded to Doudna and Charpentier.",
        "2023 — First FDA-approved CRISPR therapy (exagamglogene autotemcel) for sickle-cell disease.",
    ],
    "the-periodic-table": [
        "1869 — Dmitri Mendeleev publishes the periodic table arranged by atomic weight.",
        "1871 — Mendeleev predicts properties of gallium, scandium, and germanium.",
        "1913 — Henry Moseley orders elements by atomic number, explaining periodic law.",
        "1940s — Synthesis of transuranium elements expands the table.",
        "Present — 118 confirmed elements; the table organises all chemistry and materials science.",
    ],
    "quantum-mechanics": [
        "1900 — Max Planck proposes energy quanta to explain black-body radiation.",
        "1913 — Niels Bohr models the hydrogen atom with quantised orbits.",
        "1925–1926 — Heisenberg matrix mechanics and Schrödinger wave equation formulated.",
        "1928 — Paul Dirac's equation predicts antimatter.",
        "20th–21st century — Quantum theory enables lasers, transistors, MRI, and quantum computing research.",
    ],
    "theory-of-relativity": [
        "1905 — Einstein publishes special relativity, including E = mc².",
        "1915 — General relativity describes gravity as spacetime curvature.",
        "1919 — Eddington's solar eclipse expedition confirms light bending by gravity.",
        "2015 — LIGO detects gravitational waves from merging black holes.",
        "Present — GPS and cosmology require relativistic corrections; relativity underpins modern astrophysics.",
    ],
    "nuclear-energy-and-nuclear-science": [
        "December 1938 — Otto Hahn and Fritz Strassmann discover nuclear fission; Lise Meitner and Otto Frisch explain it.",
        "2 December 1942 — Enrico Fermi's Chicago Pile-1 achieves first controlled chain reaction.",
        "August 1945 — Atomic bombs deployed at Hiroshima and Nagasaki.",
        "1954 — Obninsk, USSR, generates the world's first grid electricity from a nuclear plant.",
        "Present — Nuclear power supplies ~10% of global electricity with very low lifecycle carbon emissions.",
    ],
    "plastics-and-synthetic-materials": [
        "1907 — Leo Baekeland invents Bakelite, the first fully synthetic plastic.",
        "1933 — Polyethylene discovered at ICI; 1935 — Wallace Carothers develops nylon at DuPont.",
        "1940s — Wartime demand accelerates polymer research and production.",
        "Present — Global plastic production exceeds 400 million tonnes per year.",
        "21st century — Microplastic pollution and recycling drive materials innovation and policy.",
    ],
    "fertilisers-and-modern-agricultural-chemistry": [
        "1909 — Fritz Haber demonstrates industrial ammonia synthesis.",
        "1910s — Carl Bosch scales the Haber process at BASF.",
        "1960s — Norman Borlaug's high-yield wheat varieties launch the Green Revolution.",
        "Present — Haber-Bosch nitrogen supports nearly half of global food production.",
        "21st century — Nitrogen runoff and greenhouse emissions drive sustainable agriculture research.",
    ],
    "telegraph": [
        "1837 — William Cooke and Charles Wheatstone patent an electric telegraph in Britain.",
        "1838 — Samuel Morse and Alfred Vail develop Morse code.",
        "1861 — First transcontinental telegraph line completed in the United States.",
        "1866 — Successful transatlantic telegraph cable links Europe and North America.",
        "19th century — Telegraphy enables Reuters, Associated Press, and real-time financial markets.",
    ],
    "telephone": [
        "7 March 1876 — Alexander Graham Bell awarded US patent for the telephone.",
        "1877 — Bell Telephone Company founded; first commercial telephone service begins.",
        "1880s–1890s — Switchboards and long-distance lines expand urban telephone networks.",
        "20th century — AT&T builds the Bell System; telephone becomes household infrastructure.",
        "21st century — Voice over IP and smartphones subsume traditional landline telephony.",
    ],
    "radio": [
        "1887 — Heinrich Hertz experimentally produces and detects electromagnetic waves.",
        "1895–1901 — Guglielmo Marconi demonstrates wireless telegraphy across increasing distances.",
        "1920 — First licensed commercial radio broadcasts in the United States and Europe.",
        "1922 — BBC founded; radio becomes mass entertainment and news medium.",
        "20th century onward — Radio principles underpin Wi-Fi, Bluetooth, radar, and mobile telephony.",
    ],
    "transistor": [
        "23 December 1947 — Bardeen, Brattain, and Shockley demonstrate the first point-contact transistor at Bell Labs.",
        "1956 — Nobel Prize in Physics awarded for the transistor invention.",
        "1954 — First commercial transistor radio (Regency TR-1).",
        "1950s — Silicon transistors replace germanium for reliability and heat tolerance.",
        "Present — Trillions of transistors power computers, phones, and embedded systems worldwide.",
    ],
    "integrated-circuit-microchip": [
        "12 September 1958 — Jack Kilby demonstrates the first integrated circuit at Texas Instruments.",
        "1959 — Robert Noyce develops the planar silicon IC at Fairchild Semiconductor.",
        "1968 — Intel founded by Noyce and Gordon Moore.",
        "1971 — Intel 4004, the first commercial microprocessor.",
        "Present — Leading chips contain tens of billions of transistors on nanometre-scale nodes.",
    ],
    "computer": [
        "1936 — Alan Turing publishes 'On Computable Numbers,' defining the universal Turing machine.",
        "1941 — Konrad Zuse completes the Z3, the first programmable electromechanical computer.",
        "1945 — ENIAC, the first general-purpose electronic computer, becomes operational.",
        "1945 — John von Neumann describes stored-program architecture.",
        "21st century — Computing pervades science, commerce, communication, and daily life globally.",
    ],
    "internet": [
        "29 October 1969 — First ARPANET message sent between UCLA and Stanford Research Institute.",
        "1974 — Vint Cerf and Bob Kahn publish the TCP/IP protocol specification.",
        "1991 — NSFNET removes commercial restrictions, accelerating public internet growth.",
        "1990s — World Wide Web and browsers make the internet accessible to non-specialists.",
        "2024 — Approximately 5 billion people use the internet; it carries exabytes of data daily.",
    ],
    "world-wide-web": [
        "March 1989 — Tim Berners-Lee proposes an information management system at CERN.",
        "6 August 1991 — First website goes live at info.cern.ch.",
        "1993 — Mosaic browser popularises graphical web browsing.",
        "1994 — W3C founded; open standards prevent proprietary lock-in.",
        "Present — Trillions of web pages; the web is the primary interface to digital information.",
    ],
    "search-engines": [
        "1990 — Alan Emtage creates Archie, the first internet search tool for FTP archives.",
        "1994 — Yahoo! and early web directories organise the growing web.",
        "1998 — Larry Page and Sergey Brin launch Google with PageRank relevance ranking.",
        "2000s — Search becomes the primary gateway to online information and commerce.",
        "2020s — Large language models begin to complement traditional keyword search.",
    ],
    "satellite-technology": [
        "4 October 1957 — Soviet Union launches Sputnik 1, the first artificial satellite.",
        "1945 — Arthur C. Clarke proposes geostationary communications satellites.",
        "1962 — Telstar 1 relays the first live transatlantic television signal.",
        "1963 — Syncom 2 achieves geostationary orbit for communications.",
        "2024 — Over 9,000 satellites orbit Earth, enabling weather, navigation, and broadband.",
    ],
    "gps-global-positioning-system": [
        "1978 — First Block I GPS satellite launched by the US Department of Defense.",
        "1993 — Full 24-satellite constellation declared operational.",
        "May 2000 — Selective availability ended, improving civilian accuracy to ~10 metres.",
        "2000s — GLONASS, Galileo, and BeiDou provide global navigation alternatives.",
        "Present — GPS underpins logistics, aviation, agriculture, and smartphone mapping worldwide.",
    ],
    "semiconductor-technology": [
        "1947 — Transistor invented at Bell Labs (see also entry 6.4).",
        "1959 — Planar process enables monolithic integrated circuits.",
        "1965 — Gordon Moore observes exponential growth in transistor density (Moore's Law).",
        "2020s — Leading-edge nodes reach 3–5 nm; EUV lithography enables further scaling.",
        "Present — Semiconductor industry revenue exceeds $600 billion annually.",
    ],
    "laser": [
        "1917 — Albert Einstein proposes stimulated emission of radiation.",
        "1954 — Charles Townes and colleagues build the first maser (microwave laser).",
        "May 1960 — Theodore Maiman demonstrates the first ruby laser.",
        "1960s onward — Lasers applied in surgery, manufacturing, fibre optics, and research.",
        "Present — Lasers enable LASIK, LiDAR, nuclear fusion research, and optical communications.",
    ],
    "fibre-optic-communication": [
        "1966 — Charles Kao and George Hockham propose low-loss glass fibres for telecommunications.",
        "1970 — Corning achieves fibre with loss below 20 dB/km.",
        "1977 — First commercial fibre-optic telephone link installed in Chicago.",
        "1988 — First transatlantic fibre-optic cable (TAT-8).",
        "Present — Fibre carries ~99% of international internet traffic.",
    ],
    "spaceflight": [
        "4 October 1957 — Sputnik 1 begins the space age.",
        "12 April 1961 — Yuri Gagarin becomes the first human in orbit.",
        "20 July 1969 — Apollo 11 astronauts land on the Moon.",
        "2000 — International Space Station begins continuous human occupation.",
        "2020s — Commercial launch (SpaceX, others) and Artemis programme renew lunar ambitions.",
    ],
    "smartphones": [
        "1994 — IBM Simon, early touchscreen smartphone concept.",
        "29 June 2007 — Apple iPhone launched, integrating phone, internet, and multi-touch interface.",
        "2008 — Google Android released as an open mobile platform.",
        "July 2008 — Apple App Store opens, creating the mobile application economy.",
        "2024 — ~6.9 billion smartphone users worldwide; primary personal computing device for billions.",
    ],
    "social-media-platforms": [
        "1997 — SixDegrees.com, among the first recognisable social networking sites.",
        "2004 — Facebook launches at Harvard; expands globally within years.",
        "2006 — Twitter (now X) introduces microblogging; Instagram follows in 2010.",
        "2016 — TikTok popularises short-form algorithmic video globally.",
        "Present — ~5 billion social media users; platforms shape news, politics, and culture.",
    ],
    "artificial-intelligence": [
        "1950 — Alan Turing proposes the imitation game (Turing Test).",
        "1956 — Dartmouth Conference coins the term 'artificial intelligence.'",
        "2012 — AlexNet demonstrates deep learning breakthrough on ImageNet.",
        "2020 — AlphaFold 2 predicts protein structures with atomic accuracy.",
        "2022–present — Large language models (GPT-4, Claude, Gemini) transform knowledge work and research.",
    ],
    "renewable-energy-technologies": [
        "1954 — Bell Labs demonstrates the first practical silicon solar cell.",
        "1970s–1980s — Oil crises accelerate wind and solar R&D.",
        "1990s–2000s — Feed-in tariffs and policy drive renewable deployment in Europe and China.",
        "2023 — Solar and wind supply ~13% of global electricity.",
        "2030s (projected) — IEA forecasts renewables become the largest electricity source worldwide.",
    ],
    "battery-technology": [
        "1800 — Alessandro Volta invents the voltaic pile, the first chemical battery.",
        "1859 — Gaston Planté invents the rechargeable lead-acid battery.",
        "1991 — Sony commercialises the lithium-ion battery.",
        "2019 — Nobel Prize in Chemistry awarded to Goodenough, Whittingham, and Yoshino for Li-ion development.",
        "2020s — Li-ion costs fall ~97% since 1991; batteries enable EVs and grid storage.",
    ],
    "electric-vehicles": [
        "1880s — Early electric carriages compete with steam and petrol vehicles.",
        "1996 — General Motors releases the EV1 in limited production.",
        "2008 — Tesla Roadster demonstrates modern lithium-ion EV performance.",
        "2022 — Global EV sales exceed 10 million vehicles per year.",
        "2030s — Many nations target phase-out of new internal-combustion vehicle sales.",
    ],
    "robotics": [
        "1961 — Unimate, the first industrial robot, installed at a General Motors plant.",
        "1970s–1990s — Robotics transforms automotive assembly lines worldwide.",
        "1999 — FDA approves the da Vinci surgical robot for minimally invasive surgery.",
        "2010s — Boston Dynamics demonstrates advanced legged locomotion (Atlas).",
        "2023 — Global robotics market exceeds $60 billion across industry, logistics, and healthcare.",
    ],
    "3d-printing-additive-manufacturing": [
        "1984 — Chuck Hull patents stereolithography (SLA), founding 3D Systems.",
        "1987 — Carl Deckard patents selective laser sintering (SLS).",
        "1989 — Scott Crump develops fused deposition modelling (FDM).",
        "2009 — RepRap movement and expired FDM patents democratise desktop 3D printing.",
        "Present — Additive manufacturing used for aerospace parts, medical implants, and bioprinting research.",
    ],
    "blockchain": [
        "October 2008 — Satoshi Nakamoto publishes the Bitcoin whitepaper.",
        "January 2009 — Bitcoin genesis block mined; first decentralised cryptocurrency network.",
        "2015 — Ethereum launches, introducing programmable smart contracts.",
        "2017–2021 — ICO boom, DeFi growth, and mainstream institutional interest.",
        "Present — Applications extend to supply chain traceability, identity, and tokenised assets.",
    ],
    "cloud-computing": [
        "1999 — Salesforce founded, pioneering software-as-a-service (SaaS).",
        "2006 — Amazon Web Services (AWS) launches Elastic Compute Cloud (EC2) and S3 storage.",
        "2008–2010 — Google Cloud Platform and Microsoft Azure enter the market.",
        "2010s — Hybrid and multi-cloud architectures become enterprise standard.",
        "Present — Cloud infrastructure underpins AI training, streaming, and global digital services.",
    ],
}

CONTRIBUTORS: dict[str, list[str]] = {
    "gunpowder": [
        "Chinese Tang Dynasty alchemists — earliest documented gunpowder formulae.",
        "Islamic and European scholars — transmission and military adaptation (13th century onward).",
        "Joseph Needham — documentation of Chinese science and gunpowder history.",
    ],
    "the-printing-press": [
        "Bi Sheng (c. 990–1051 CE) — movable type in Song Dynasty China.",
        "Johannes Gutenberg (c. 1398–1468) — European printing press, Mainz.",
        "Elizabeth L. Eisenstein — historian of print culture and the printing revolution.",
    ],
    "the-scientific-method": [
        "Ibn al-Haytham (Alhazen, c. 965–1040) — experimental optics and scientific method.",
        "Francis Bacon (1561–1626) — inductive reasoning and institutional science.",
        "Galileo Galilei (1564–1642) — quantitative observation and experimental physics.",
        "Royal Society fellows — peer review and reproducible experiment.",
    ],
    "the-telescope": [
        "Hans Lipperhey (c. 1570–1619) — refracting telescope patent, 1608.",
        "Galileo Galilei — first systematic astronomical observations, 1610.",
        "Isaac Newton (1643–1727) — reflecting telescope design, 1668.",
        "NASA, ESA, and international partners — Hubble, JWST, and modern observatories.",
    ],
    "the-microscope": [
        "Zacharias Janssen (c. 1580–1638) — compound microscope.",
        "Antoni van Leeuwenhoek (1632–1723) — high-power single-lens microscopy.",
        "Robert Hooke (1635–1703) — Micrographia and cell observation.",
        "Ernst Ruska (1906–1988) — electron microscopy.",
    ],
    "newtonian-mechanics": [
        "Isaac Newton (1643–1727) — Principia Mathematica, laws of motion and gravitation.",
        "Gottfried Wilhelm Leibniz (1646–1716) — calculus (parallel development).",
        "Leonhard Euler, Joseph-Louis Lagrange, Pierre-Simon Laplace — classical mechanics extensions.",
    ],
    "steam-engine": [
        "Thomas Newcomen (1664–1729) — atmospheric steam engine, 1712.",
        "James Watt (1736–1819) — separate condenser and efficiency improvements.",
        "Richard Trevithick (1771–1833) — high-pressure steam and locomotion.",
    ],
    "electricity-generation-and-distribution": [
        "Michael Faraday (1791–1867) — electromagnetic induction.",
        "Thomas Edison (1847–1931) — DC distribution and incandescent lighting.",
        "Nikola Tesla (1856–1943) — alternating current systems.",
        "George Westinghouse (1846–1914) — AC power transmission.",
    ],
    "electromagnetism": [
        "Hans Christian Ørsted (1777–1851) — link between electricity and magnetism.",
        "André-Marie Ampère (1775–1836) — electrodynamics.",
        "Michael Faraday — induction and field concept.",
        "James Clerk Maxwell (1831–1879) — unified electromagnetic theory.",
        "Heinrich Hertz (1857–1894) — experimental radio waves.",
    ],
    "internal-combustion-engine": [
        "Étienne Lenoir (1822–1900) — first commercial ICE, 1859.",
        "Nikolaus Otto (1832–1891) — four-stroke cycle, 1876.",
        "Rudolf Diesel (1858–1913) — compression-ignition engine, 1897.",
    ],
    "automobile": [
        "Karl Benz (1844–1929) — Patent-Motorwagen, 1885.",
        "Gottlieb Daimler (1834–1900) and Wilhelm Maybach — high-speed engines.",
        "Henry Ford (1863–1947) — assembly-line mass production.",
    ],
    "airplane": [
        "Orville and Wilbur Wright — first powered flight, 1903.",
        "Louis Blériot — English Channel crossing, 1909.",
        "Frank Whittle (1907–1996) — jet engine pioneer.",
    ],
    "refrigeration": [
        "Jacob Perkins (1766–1849) — vapour-compression patent, 1834.",
        "Carl von Linde (1842–1934) — industrial refrigeration.",
        "Clarence Birdseye (1886–1956) — commercial frozen food processes.",
    ],
    "vaccination": [
        "Edward Jenner (1749–1823) — smallpox vaccine, 1796.",
        "Louis Pasteur (1822–1895) — rabies and anthrax vaccines.",
        "Jonas Salk (1914–1995) — inactivated polio vaccine, 1955.",
        "World Health Organization — smallpox eradication programme.",
    ],
    "antibiotics": [
        "Alexander Fleming (1881–1955) — penicillin discovery, 1928.",
        "Howard Florey (1898–1968) and Ernst Chain (1906–1979) — purification and clinical use.",
        "Selman Waksman (1888–1973) — streptomycin and soil microbiology.",
    ],
    "germ-theory-of-disease": [
        "Ignaz Semmelweis (1818–1865) — handwashing and puerperal fever.",
        "John Snow (1813–1858) — cholera epidemiology.",
        "Louis Pasteur — germ theory and pasteurisation.",
        "Robert Koch (1843–1910) — bacteriology and Koch's postulates.",
    ],
    "anaesthesia": [
        "Crawford Long (1815–1878) — ether anaesthesia, 1842.",
        "William Morton (1819–1868) — public ether demonstration, 1846.",
        "James Young Simpson (1811–1870) — chloroform in obstetrics, 1847.",
    ],
    "x-rays-and-medical-imaging": [
        "Wilhelm Conrad Röntgen (1845–1923) — X-ray discovery, 1895.",
        "Godfrey Hounsfield (1919–2004) and Allan Cormack (1924–1998) — CT scanning.",
        "Paul Lauterbur (1929–2007) and Peter Mansfield (1933–2017) — MRI development.",
    ],
    "sanitation-and-clean-water-systems": [
        "John Snow — epidemiological water-source investigation.",
        "Joseph Bazalgette (1819–1891) — London sewer engineering.",
        "Edwin Chadwick (1800–1890) — public health reform.",
        "World Health Organization and UNICEF — global water and sanitation programmes.",
    ],
    "dna-structure-and-molecular-genetics": [
        "Oswald Avery (1877–1955) — DNA as genetic material.",
        "Rosalind Franklin (1920–1958) — X-ray crystallography of DNA.",
        "James Watson (1928–) and Francis Crick (1916–2004) — double-helix model.",
        "Erwin Chargaff (1905–2002) — base-pairing rules.",
    ],
    "human-genome-sequencing": [
        "Human Genome Project international consortium — public sequencing effort.",
        "Francis Collins — NHGRI leadership of the HGP.",
        "Craig Venter — Celera Genomics parallel private effort.",
        "Telomere-to-Telomere (T2T) Consortium — gapless genome, 2022.",
    ],
    "crispr-gene-editing": [
        "Jennifer Doudna and Emmanuelle Charpentier — programmable Cas9 editing, 2012.",
        "Feng Zhang — parallel CRISPR applications in mammalian cells.",
        "Emmanuelle Charpentier and Jennifer Doudna — Nobel Prize in Chemistry, 2020.",
    ],
    "the-periodic-table": [
        "Dmitri Mendeleev (1834–1907) — periodic law and predictive table, 1869.",
        "Lothar Meyer (1830–1895) — independent periodic arrangement.",
        "Henry Moseley (1887–1915) — atomic-number ordering.",
    ],
    "quantum-mechanics": [
        "Max Planck (1858–1947) — quantum hypothesis, 1900.",
        "Niels Bohr (1885–1962) — atomic model.",
        "Werner Heisenberg (1901–1976) and Erwin Schrödinger (1887–1961) — quantum formalism.",
        "Paul Dirac (1902–1984) — relativistic quantum mechanics.",
    ],
    "theory-of-relativity": [
        "Albert Einstein (1879–1955) — special and general relativity.",
        "Arthur Eddington (1882–1944) — 1919 eclipse confirmation.",
        "Kip Thorne, Rainer Weiss, Barry Barish — gravitational-wave detection (LIGO).",
    ],
    "nuclear-energy-and-nuclear-science": [
        "Otto Hahn (1879–1968) and Lise Meitner (1878–1968) — nuclear fission.",
        "Enrico Fermi (1901–1954) — first controlled chain reaction.",
        "Manhattan Project scientists — wartime nuclear development.",
    ],
    "plastics-and-synthetic-materials": [
        "Leo Baekeland (1863–1944) — Bakelite, 1907.",
        "Wallace Carothers (1896–1937) — nylon at DuPont.",
        "ICI and DuPont polymer chemists — polyethylene and modern plastics.",
    ],
    "fertilisers-and-modern-agricultural-chemistry": [
        "Fritz Haber (1868–1934) — ammonia synthesis.",
        "Carl Bosch (1874–1940) — industrial Haber process scaling.",
        "Norman Borlaug (1914–2009) — Green Revolution wheat breeding.",
    ],
    "telegraph": [
        "Samuel Morse (1791–1872) and Alfred Vail (1807–1859) — Morse code.",
        "William Cooke (1806–1879) and Charles Wheatstone (1802–1875) — electric telegraph.",
    ],
    "telephone": [
        "Alexander Graham Bell (1847–1922) — telephone patent, 1876.",
        "Elisha Gray (1835–1901) and Antonio Meucci (1808–1889) — disputed priority.",
        "Theodore Vail — AT&T network expansion.",
    ],
    "radio": [
        "Heinrich Hertz (1857–1894) — electromagnetic wave experiments.",
        "Guglielmo Marconi (1874–1937) — practical wireless telegraphy.",
        "Nikola Tesla — early radio and wireless power research.",
    ],
    "transistor": [
        "John Bardeen (1908–1991), Walter Brattain (1902–1987), William Shockley (1910–1989) — Bell Labs, 1947.",
    ],
    "integrated-circuit-microchip": [
        "Jack Kilby (1923–2005) — first integrated circuit, Texas Instruments.",
        "Robert Noyce (1927–1990) — planar silicon IC, Fairchild/Intel.",
        "Gordon Moore (1929–2023) — Moore's Law observation.",
    ],
    "computer": [
        "Alan Turing (1912–1954) — computability theory.",
        "Konrad Zuse (1910–1995) — Z3 programmable computer.",
        "John von Neumann (1903–1957) — stored-program architecture.",
        "ENIAC team (Mauchly, Eckert, and colleagues) — electronic computation.",
    ],
    "internet": [
        "ARPANET researchers (Kleinrock, Roberts, and others) — packet switching.",
        "Vint Cerf and Bob Kahn — TCP/IP protocols.",
        "Tim Berners-Lee — World Wide Web layer.",
    ],
    "world-wide-web": [
        "Tim Berners-Lee (1955–) — HTTP, HTML, URI standards.",
        "Robert Cailliau — CERN web collaboration.",
        "Marc Andreessen — Mosaic browser popularisation.",
    ],
    "search-engines": [
        "Alan Emtage — Archie, 1990.",
        "Larry Page and Sergey Brin — Google PageRank, 1998.",
    ],
    "satellite-technology": [
        "Sergei Korolev (1907–1966) — Soviet space programme.",
        "Arthur C. Clarke (1917–2008) — geostationary orbit concept.",
        "NASA and international space agencies — communications and Earth-observation satellites.",
    ],
    "gps-global-positioning-system": [
        "Roger L. Easton (1921–2014), Ivan Getting (1912–2003), Bradford Parkinson (1935–) — GPS development.",
        "US Department of Defense — NAVSTAR GPS constellation.",
    ],
    "semiconductor-technology": [
        "Bell Labs — transistor invention.",
        "Robert Noyce and Gordon Moore — Intel and planar process.",
        "Morris Chang — TSMC foundry model.",
        "ASML — extreme ultraviolet lithography systems.",
    ],
    "laser": [
        "Albert Einstein — stimulated emission theory, 1917.",
        "Charles Townes (1915–2015) and Arthur Schawlow (1921–1999) — maser/laser theory.",
        "Theodore Maiman (1927–2007) — first ruby laser, 1960.",
    ],
    "fibre-optic-communication": [
        "Charles K. Kao (1933–2018) — low-loss fibre theory (Nobel Prize 2009).",
        "Robert Maurer, Donald Keck, Peter Schultz — Corning low-loss fibre, 1970.",
    ],
    "spaceflight": [
        "Sergei Korolev — Soviet launch vehicles.",
        "Wernher von Braun (1912–1977) — US rocket programme.",
        "Yuri Gagarin (1934–1968) and Neil Armstrong (1930–2012) — human spaceflight milestones.",
        "NASA, Roscosmos, ESA, CNSA, and commercial providers — ongoing programmes.",
    ],
    "smartphones": [
        "IBM — Simon Personal Communicator, 1994.",
        "Steve Jobs and Apple design team — iPhone, 2007.",
        "Andy Rubin and Google — Android platform, 2008.",
    ],
    "social-media-platforms": [
        "Mark Zuckerberg — Facebook/Meta.",
        "Jack Dorsey — Twitter.",
        "Kevin Systrom and Mike Krieger — Instagram.",
        "ByteDance — TikTok global platform.",
    ],
    "artificial-intelligence": [
        "Alan Turing — foundations of computation and AI.",
        "John McCarthy (1927–2011) — coined 'artificial intelligence,' 1956.",
        "Geoffrey Hinton, Yann LeCun, Yoshua Bengio — deep learning pioneers.",
        "OpenAI, Google DeepMind, Anthropic, and others — large language models.",
    ],
    "renewable-energy-technologies": [
        "Bell Labs researchers — silicon solar cell, 1954.",
        "Danish and German wind-engineering pioneers — modern wind turbines.",
        "International Renewable Energy Agency (IRENA) — global deployment data.",
    ],
    "battery-technology": [
        "Alessandro Volta (1745–1827) — voltaic pile.",
        "John Goodenough (1922–2023), M. Stanley Whittingham, Akira Yoshino — lithium-ion battery.",
    ],
    "electric-vehicles": [
        "Charles Jeantaud — early electric carriages, 1880s.",
        "General Motors — EV1 programme.",
        "Martin Eberhard, Marc Tarpenning, Elon Musk — Tesla Motors.",
    ],
    "robotics": [
        "George Devol (1912–2011) — Unimate industrial robot.",
        "Joseph Engelberger (1925–2015) — robotics commercialisation.",
        "Rodney Brooks — behaviour-based robotics (iRobot, Boston Dynamics era).",
    ],
    "3d-printing-additive-manufacturing": [
        "Chuck Hull — stereolithography, 1984.",
        "Carl Deckard — selective laser sintering.",
        "Scott Crump — fused deposition modelling (Stratasys).",
    ],
    "blockchain": [
        "Satoshi Nakamoto (pseudonym) — Bitcoin whitepaper and genesis block.",
        "Vitalik Buterin — Ethereum and smart contracts.",
    ],
    "cloud-computing": [
        "Marc Benioff — Salesforce and SaaS model.",
        "Andy Jassy and Amazon Web Services team — EC2 and S3, 2006.",
        "Google Cloud and Microsoft Azure engineering teams — global cloud platforms.",
    ],
}
